name: Build and deploy to Kuroco front(dev)
on:
  push:
    branches:
      - dev
  issue_comment:
    types: [created, edited]
  workflow_dispatch:
env:
  BASE_URL: ${{secrets.BASE_URL_DEV}}
  NODE_ENV: develop
jobs:
  # for Pull Request (exclude merged)
  pullreq_build:
    name: Build(pullreq)
    if: (github.repository == 'HisashiHasebe/hasebetest-kuroco4' && github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/kuroco stage') && github.event.issue.pull_request != null)
    runs-on: ubuntu-latest
    steps:
      - name: "Get branch name and sha"
        id: get_branch
        run: |
          PR=$(curl -H "Authorization: token d878a7b809ee24d52f239487dd2becb4" https://hasebetest4-dev.g.kuroco.app/direct/menu/github/?pr=${{ github.event.issue.pull_request.url }})
          echo "branch=$(echo $PR | jq -r '.ref')" >> $GITHUB_OUTPUT
          echo "sha=$(echo $PR | jq -r '.sha')" >> $GITHUB_OUTPUT
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.get_branch.outputs.branch }}
      - name: Copy kuroco_front.json
        run:  cp static/kuroco_front_dev.json static/kuroco_front.json
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Generate
        run: npm run generate
        # - name: Zip artifact for upload
        #  run: cd dist && zip ../dist.zip . -r
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.get_branch.outputs.sha }}-${{ github.run_id }}
          path: dist
          retention-days: 7
      - name: Wait for Artifact download
        run: sleep 15
      - name: Webhook
        uses: diverta/workflow-webhook@v2
        env:
          webhook_url: "https://hasebetest4-dev.g.kuroco.app/direct/menu/github/"
          webhook_secret: "d878a7b809ee24d52f239487dd2becb4"
          data: '{"single_zip":"0","domain":"hasebetest4-dev.g.kuroco-front.app","pr":"${{ github.event.issue.pull_request.url }}",  "repository":"${{ github.repository }}", "run_id":"${{ github.run_id }}", "hash":"${{ steps.get_branch.outputs.sha }}"}'
          
  #for Push
  pushed_build:
    name: Build(pushed)
    if: (github.repository == 'HisashiHasebe/hasebetest-kuroco4' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Copy kuroco_front.json
        run:  cp static/kuroco_front_dev.json static/kuroco_front.json
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Generate
        run: npm run generate
        # - name: Zip artifact for upload
        #  run: cd dist && zip ../dist.zip . -r
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.sha }}-${{ github.run_id }}
          path: dist
          retention-days: 7
      - name: Webhook
        uses: diverta/workflow-webhook@v2
        env:
          webhook_url: "https://hasebetest4-dev.g.kuroco.app/direct/menu/github/"
          webhook_secret: "d878a7b809ee24d52f239487dd2becb4"
          data: '{"single_zip":"0","domain":"hasebetest4-dev.g.kuroco-front.app", "repository":"${{ github.repository }}", "run_id":"${{ github.run_id }}", "hash":"${{ github.sha }}"}'
